description = "Large Language Model As A Service Providers"

[providers]

[providers.deepseek]
description = "DeepSeek Official"
api_key_name = "DEEPSEEK_API_KEY"
base_url = "https://api.deepseek.com"
beta_base_url = "https://api.deepseek.com/beta"
chat_model_id = "deepseek-chat"
coder_model_id = "deepseek-chat"
reasoner_model_id = "deepseek-reasoner"

[providers.aliyun_deepseek]
description = "DeepSeek on Aliyun"
api_key_name = "ALIYUN_API_KEY"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
beta_base_url = ""
chat_model_id = "deepseek-v3"
coder_model_id = "deepseek-v3"
reasoner_model_id = "deepseek-r1"

[providers.aliyun_qwen]
description = "Qwen Official"
api_key_name = "ALIYUN_API_KEY"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
beta_base_url = ""
chat_model_id = "qwen-max"
coder_model_id = "qwen-coder-plus"
reasoner_model_id = "qwq-plus"

[providers.moonshot]
description = "Moonshot Official"
api_key_name = "MOONSHOT_API_KEY"
base_url = "https://api.moonshot.cn/v1"
beta_base_url = ""
chat_model_id = "kimi-k2-0711-preview"
coder_model_id = "kimi-k2-0711-preview"
reasoner_model_id = "kimi-thinking-preview"

[providers.openrouter]
description = "OpenRouter"
api_key_name = "OPENROUTER_API_KEY"
base_url = "https://openrouter.ai/api/v1"
beta_base_url = ""
chat_model_id = "google/gemini-2.5-flash-preview-05-20"
coder_model_id = "google/gemini-2.5-flash-preview-05-20"
reasoner_model_id = "google/gemini-2.5-flash-preview-05-20:thinking"

[providers.ecnu]
description = "ECNU"
api_key_name = "ECNU_API_KEY"
base_url = "https://chat.ecnu.edu.cn/open/api/v1"
beta_base_url = ""
chat_model_id = "ecnu-max"
coder_model_id = ""
reasoner_model_id = "ecnu-reasoner"
default_model_type = "reasoner"

[providers.local]
description = "Local"
api_key_name = "LOCAL_API_KEY"
base_url = "http://localhost:5810/v1"
beta_base_url = ""
chat_model_id = "qwen3-nothink"
coder_model_id = "devstral"
reasoner_model_id = "qwen3"

[providers.lmstudio]
description = "LM Studio"
api_key_name = "LM_STUDIO_API_KEY"
base_url = "http://127.0.0.1:1234/v1"
beta_base_url = ""
chat_model_id = "qwen3-30b-a3b-dwq-053125"
coder_model_id = "devstral-small-2505"
reasoner_model_id = "qwen3-30b-a3b-dwq-053125"

[providers.ollama]
description = "Ollama"
api_key_name = "OLLAMA_API_KEY"
base_url = "http://localhost:11434/v1"
beta_base_url = ""
chat_model_id = "qwen3"
coder_model_id = ""
reasoner_model_id = ""

[defaults]
provider = "aliyun_qwen"
model_type = "chat"

[aliases]
qwen = "aliyun_qwen"
